pvc:
  #If not specified will default to oci
  storageClassName: "standard"
  accessModes: ReadWriteOnce
  #Minimum size on OCI is 50Gi, if set smaller the deployment will fail
  storageSize: 10Gi

service:
  type: ClusterIP
  port: 1521

replicaCount: 1

image:
  repository: ovrdoz/docker-oracle-xe-11g 
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: 
  limits:
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
