apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "oracledb.fullname" . }}
  labels:
    app: {{ template "oracledb.name" . }}
    chart: {{ template "oracledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
