apiVersion: v1
kind: Service
metadata:
  name: oracledb
  labels:
    app: {{ template "oracledb.name" . }}
    chart: {{ template "oracledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: oracledb-port
  selector:
    app: {{ template "oracledb.name" . }}
    release: {{ .Release.Name }}